/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["accents_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accents/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["accents_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apparences/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["apparences_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apparences/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["apparences_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/competences-artistiques/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["competences_artistiques_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/competences-artistiques/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["competences_artistiques_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/competences-conduite/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["competences_conduite_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/competences-conduite/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["competences_conduite_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/competences-particulieres/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["competences_particulieres_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/competences-particulieres/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["competences_particulieres_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connexion/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Ouvre une session à partir d'un identifiant et d'un mot de passe.
         *
         *     `csrf_protect` est explicite : DRF exempte ses vues du CSRF et ne le vérifie
         *     qu'au moment d'authentifier une session existante. Sans ce décorateur, un site
         *     tiers pourrait connecter la victime sur un compte qu'il contrôle (login CSRF).
         */
        post: operations["connexion_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/costumes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["costumes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/costumes/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["costumes_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deconnexion/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Ferme la session courante. */
        post: operations["deconnexion_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/departements/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["departements_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/departements/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["departements_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["instruments_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["instruments_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/langues/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["langues_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/langues/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["langues_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metiers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["metiers_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metiers/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["metiers_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/permis/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["permis_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/permis/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["permis_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Upload et suppression des photos d'un profil (multipart). */
        get: operations["photos_list"];
        put?: never;
        /** @description Upload et suppression des photos d'un profil (multipart). */
        post: operations["photos_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Upload et suppression des photos d'un profil (multipart). */
        get: operations["photos_retrieve"];
        /** @description Upload et suppression des photos d'un profil (multipart). */
        put: operations["photos_update"];
        post?: never;
        /** @description Upload et suppression des photos d'un profil (multipart). */
        delete: operations["photos_destroy"];
        options?: never;
        head?: never;
        /** @description Upload et suppression des photos d'un profil (multipart). */
        patch: operations["photos_partial_update"];
        trace?: never;
    };
    "/api/prestations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["prestations_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prestations/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["prestations_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profils/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Recherche à facettes, consultation et saisie d'un profil.
         *
         *     `ensure_csrf_cookie` sur la liste : le front récupère le cookie CSRF en
         *     affichant la planche, avant tout envoi de formulaire.
         */
        get: operations["profils_list"];
        put?: never;
        /**
         * @description Recherche à facettes, consultation et saisie d'un profil.
         *
         *     `ensure_csrf_cookie` sur la liste : le front récupère le cookie CSRF en
         *     affichant la planche, avant tout envoi de formulaire.
         */
        post: operations["profils_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profils/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Recherche à facettes, consultation et saisie d'un profil.
         *
         *     `ensure_csrf_cookie` sur la liste : le front récupère le cookie CSRF en
         *     affichant la planche, avant tout envoi de formulaire.
         */
        get: operations["profils_retrieve"];
        /**
         * @description Recherche à facettes, consultation et saisie d'un profil.
         *
         *     `ensure_csrf_cookie` sur la liste : le front récupère le cookie CSRF en
         *     affichant la planche, avant tout envoi de formulaire.
         */
        put: operations["profils_update"];
        post?: never;
        /**
         * @description Recherche à facettes, consultation et saisie d'un profil.
         *
         *     `ensure_csrf_cookie` sur la liste : le front récupère le cookie CSRF en
         *     affichant la planche, avant tout envoi de formulaire.
         */
        delete: operations["profils_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Recherche à facettes, consultation et saisie d'un profil.
         *
         *     `ensure_csrf_cookie` sur la liste : le front récupère le cookie CSRF en
         *     affichant la planche, avant tout envoi de formulaire.
         */
        patch: operations["profils_partial_update"];
        trace?: never;
    };
    "/api/registres/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["registres_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/registres/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["registres_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Qui est connecté, et pose le cookie CSRF.
         *
         *     Ouverte en anonyme à dessein : la page de connexion a besoin du cookie CSRF
         *     pour poster, et elle ne peut pas l'obtenir d'un endpoint qui la rejette.
         *     Ne divulgue rien d'autre que « personne n'est connecté ».
         */
        get: operations["session_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sports/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["sports_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sports/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["sports_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/types-experience/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["types_experience_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/types-experience/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["types_experience_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/types-vehicule/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["types_vehicule_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/types-vehicule/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["types_vehicule_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zones-mobilite/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["zones_mobilite_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zones-mobilite/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Listes qui alimentent le rail de filtres. */
        get: operations["zones_mobilite_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Alimente les listes du rail de filtres. */
        Accent: {
            readonly id: number;
            nom: string;
        };
        /** @description Alimente les listes du rail de filtres. */
        Apparence: {
            readonly id: number;
            nom: string;
        };
        /** @enum {unknown} */
        BlankEnum: "";
        /**
         * @description * `non` - Non
         *     * `degarni` - Dégarni
         *     * `chauve` - Chauve
         * @enum {string}
         */
        CalvitieEnum: "non" | "degarni" | "chauve";
        /**
         * @description * `collectif` - Sport collectif
         *     * `individuel` - Sport individuel
         * @enum {string}
         */
        CategorieEnum: "collectif" | "individuel";
        /** @description Alimente les listes du rail de filtres. */
        CompetenceArtistique: {
            readonly id: number;
            nom: string;
        };
        /** @description Une ligne de through model telle que la poste le formulaire. */
        CompetenceArtistiqueEcriture: {
            niveau: string;
            competence: number;
        };
        /** @description Alimente les listes du rail de filtres. */
        CompetenceConduite: {
            readonly id: number;
            nom: string;
        };
        /** @description Alimente les listes du rail de filtres. */
        CompetenceParticuliere: {
            readonly id: number;
            nom: string;
        };
        /**
         * @description * `seul` - Seul
         *     * `couple` - Couple
         *     * `fratrie` - Fratrie
         *     * `famille` - Famille
         *     * `amis` - Groupe d'amis
         *     * `duo` - Duo
         *     * `trio` - Trio
         *     * `groupe_sportif` - Groupe sportif
         *     * `groupe_pro` - Groupe professionnel
         * @enum {string}
         */
        CompositionEnum: "seul" | "couple" | "fratrie" | "famille" | "amis" | "duo" | "trio" | "groupe_sportif" | "groupe_pro";
        Connexion: {
            identifiant: string;
            mot_de_passe: string;
        };
        /** @description Alimente les listes du rail de filtres. */
        Costume: {
            readonly id: number;
            nom: string;
        };
        /**
         * @description * `blond` - Blond
         *     * `chatain` - Châtain
         *     * `brun` - Brun
         *     * `noir` - Noir
         *     * `roux` - Roux
         *     * `gris` - Gris
         *     * `blanc` - Blanc
         *     * `colore` - Coloré (fantaisie)
         * @enum {string}
         */
        CouleurCheveuxEnum: "blond" | "chatain" | "brun" | "noir" | "roux" | "gris" | "blanc" | "colore";
        /**
         * @description * `marron` - Marron
         *     * `bleu` - Bleu
         *     * `vert` - Vert
         *     * `noisette` - Noisette
         *     * `gris` - Gris
         *     * `noir` - Noir
         * @enum {string}
         */
        CouleurYeuxEnum: "marron" | "bleu" | "vert" | "noisette" | "gris" | "noir";
        Departement: {
            readonly id: number;
            code: string;
            nom: string;
            readonly region: string;
        };
        /**
         * @description * `immediate` - Immédiate
         *     * `sous_48h` - Sous 48 h
         *     * `week_ends` - Week-ends uniquement
         *     * `vacances` - Vacances scolaires
         *     * `sur_demande` - Sur demande
         * @enum {string}
         */
        DisponibiliteEnum: "immediate" | "sous_48h" | "week_ends" | "vacances" | "sur_demande";
        /**
         * @description * `vacances` - Vacances scolaires uniquement
         *     * `mercredi` - Mercredi et week-ends
         *     * `hors_scolaire` - Hors temps scolaire
         *     * `sans_contrainte` - Sans contrainte particulière
         * @enum {string}
         */
        DisponibiliteScolaireEnum: "vacances" | "mercredi" | "hors_scolaire" | "sans_contrainte";
        /** @description Alimente les listes du rail de filtres. */
        Instrument: {
            readonly id: number;
            nom: string;
        };
        /** @description Une ligne de through model telle que la poste le formulaire. */
        InstrumentEcriture: {
            niveau: string;
            instrument: number;
        };
        /** @description Alimente les listes du rail de filtres. */
        Langue: {
            readonly id: number;
            nom: string;
        };
        /** @description Une ligne de through model telle que la poste le formulaire. */
        LangueEcriture: {
            niveau: string;
            langue: number;
            accent?: number | null;
        };
        /**
         * @description * `courts` - Courts
         *     * `mi_longs` - Mi-longs
         *     * `longs` - Longs
         * @enum {string}
         */
        LongueurCheveuxEnum: "courts" | "mi_longs" | "longs";
        /** @description Alimente les listes du rail de filtres. */
        Metier: {
            readonly id: number;
            nom: string;
        };
        /**
         * @description Présence d'un dossier mineur, sans exposer l'identité du responsable légal
         *     dans une réponse de recherche.
         */
        Mineur: {
            readonly autorisation_parentale_signee: boolean;
            readonly autorisation_travail_obtenue: boolean;
            readonly disponibilite_scolaire: string;
        };
        MineurEcriture: {
            responsable_legal_nom: string;
            responsable_legal_prenom: string;
            responsable_legal_lien: components["schemas"]["ResponsableLegalLienEnum"];
            responsable_legal_telephone?: string;
            responsable_legal_email?: string;
            autorisation_parentale_signee?: boolean;
            /** Format: date */
            autorisation_parentale_le?: string | null;
            autorisation_travail_obtenue?: boolean;
            autorisation_travail_reference?: string;
            /** Format: date */
            autorisation_travail_expire_le?: string | null;
            disponibilite_scolaire?: components["schemas"]["DisponibiliteScolaireEnum"] | components["schemas"]["BlankEnum"];
            remarques?: unknown;
        };
        PaginatedProfilListeList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ProfilListe"][];
        };
        PatchedPhotoEcriture: {
            readonly id?: number;
            profil?: number;
            type?: components["schemas"]["TypeEnum"];
            /** Format: uri */
            image?: string;
            /** Format: date */
            prise_le?: string | null;
        };
        /**
         * @description Saisie d'un profil depuis le front (voir decisions/0001).
         *
         *     Les through models arrivent en listes imbriquées ; DRF ne sait pas les écrire
         *     seul, d'où le `create`/`update` explicite plus bas.
         */
        PatchedProfilEcriture: {
            readonly id?: number;
            sports?: components["schemas"]["SportEcriture"][];
            langues?: components["schemas"]["LangueEcriture"][];
            instruments?: components["schemas"]["InstrumentEcriture"][];
            competences_artistiques?: components["schemas"]["CompetenceArtistiqueEcriture"][];
            vehicules?: components["schemas"]["VehiculeEcriture"][];
            mineur?: components["schemas"]["MineurEcriture"] | null;
            reference?: string | null;
            nom?: string;
            prenom?: string;
            nom_artiste?: string;
            sexe?: components["schemas"]["SexeEnum"] | components["schemas"]["BlankEnum"];
            /** Format: date */
            date_naissance?: string | null;
            age_apparent_min?: number | null;
            age_apparent_max?: number | null;
            telephone?: string;
            email?: string;
            disponibilite?: components["schemas"]["DisponibiliteEnum"] | components["schemas"]["BlankEnum"];
            deja_figurant?: boolean;
            nombre_tournages?: number | null;
            taille_cm?: number | null;
            poids_kg?: number | null;
            pointure?: number | null;
            taille_vetement?: components["schemas"]["TailleVetementEnum"] | components["schemas"]["BlankEnum"];
            taille_pantalon?: number | null;
            tour_poitrine_cm?: number | null;
            tour_taille_cm?: number | null;
            tour_hanches_cm?: number | null;
            couleur_yeux?: components["schemas"]["CouleurYeuxEnum"] | components["schemas"]["BlankEnum"];
            couleur_cheveux?: components["schemas"]["CouleurCheveuxEnum"] | components["schemas"]["BlankEnum"];
            type_cheveux?: components["schemas"]["TypeCheveuxEnum"] | components["schemas"]["BlankEnum"];
            longueur_cheveux?: components["schemas"]["LongueurCheveuxEnum"] | components["schemas"]["BlankEnum"];
            cheveux_colores?: boolean;
            barbe?: boolean;
            moustache?: boolean;
            calvitie?: components["schemas"]["CalvitieEnum"] | components["schemas"]["BlankEnum"];
            tatouages_visibles?: boolean;
            piercings?: boolean;
            lunettes?: boolean;
            lentilles?: boolean;
            profil_multiculturel?: boolean;
            composition?: components["schemas"]["CompositionEnum"] | components["schemas"]["BlankEnum"];
            ville?: string;
            distance_max_km?: number | null;
            peut_dormir_sur_place?: boolean;
            vehicule_personnel_disponible?: boolean;
            besoin_transport?: boolean;
            /** Format: date */
            consentement_obtenu_le?: string | null;
            source_consentement?: string;
            actif?: boolean;
            reseaux_sociaux?: unknown;
            autres_caracteristiques?: unknown;
            notes?: unknown;
            departement?: number | null;
            registres?: number[];
            apparences?: number[];
            permis?: number[];
            competences_conduite?: number[];
            metiers?: number[];
            competences_particulieres?: number[];
            costumes?: number[];
            zones_mobilite?: number[];
            types_experience?: number[];
            prestations_acceptees?: number[];
        };
        Permis: {
            readonly id: number;
            code: string;
            libelle?: string;
        };
        Photo: {
            readonly id: number;
            type: components["schemas"]["TypeEnum"];
            readonly type_libelle: string;
            readonly url: string;
            /** Format: date */
            prise_le?: string | null;
        };
        PhotoEcriture: {
            readonly id: number;
            profil: number;
            type: components["schemas"]["TypeEnum"];
            /** Format: uri */
            image: string;
            /** Format: date */
            prise_le?: string | null;
        };
        ProfilCompetenceArtistique: {
            readonly competence: string;
            niveau: components["schemas"]["ProfilCompetenceArtistiqueNiveauEnum"];
            readonly niveau_libelle: string;
        };
        /**
         * @description * `1` - Débutant
         *     * `2` - Amateur
         *     * `3` - Confirmé
         *     * `4` - Professionnel
         * @enum {string}
         */
        ProfilCompetenceArtistiqueNiveauEnum: "1" | "2" | "3" | "4";
        ProfilDetail: {
            readonly id: number;
            reference?: string | null;
            prenom: string;
            nom: string;
            nom_artiste?: string;
            sexe?: components["schemas"]["SexeEnum"] | components["schemas"]["BlankEnum"];
            readonly age: number;
            readonly est_mineur: boolean;
            age_apparent_min?: number | null;
            age_apparent_max?: number | null;
            telephone?: string;
            email?: string;
            ville?: string;
            readonly departement: components["schemas"]["Departement"];
            distance_max_km?: number | null;
            peut_dormir_sur_place?: boolean;
            vehicule_personnel_disponible?: boolean;
            besoin_transport?: boolean;
            taille_cm?: number | null;
            poids_kg?: number | null;
            pointure?: number | null;
            taille_vetement?: components["schemas"]["TailleVetementEnum"] | components["schemas"]["BlankEnum"];
            taille_pantalon?: number | null;
            tour_poitrine_cm?: number | null;
            tour_taille_cm?: number | null;
            tour_hanches_cm?: number | null;
            couleur_yeux?: components["schemas"]["CouleurYeuxEnum"] | components["schemas"]["BlankEnum"];
            couleur_cheveux?: components["schemas"]["CouleurCheveuxEnum"] | components["schemas"]["BlankEnum"];
            type_cheveux?: components["schemas"]["TypeCheveuxEnum"] | components["schemas"]["BlankEnum"];
            longueur_cheveux?: components["schemas"]["LongueurCheveuxEnum"] | components["schemas"]["BlankEnum"];
            cheveux_colores?: boolean;
            barbe?: boolean;
            moustache?: boolean;
            calvitie?: components["schemas"]["CalvitieEnum"] | components["schemas"]["BlankEnum"];
            tatouages_visibles?: boolean;
            piercings?: boolean;
            lunettes?: boolean;
            lentilles?: boolean;
            profil_multiculturel?: boolean;
            composition?: components["schemas"]["CompositionEnum"] | components["schemas"]["BlankEnum"];
            disponibilite?: components["schemas"]["DisponibiliteEnum"] | components["schemas"]["BlankEnum"];
            deja_figurant?: boolean;
            nombre_tournages?: number | null;
            readonly apparences: string[];
            readonly registres: string[];
            readonly metiers: string[];
            readonly competences_particulieres: string[];
            readonly costumes: string[];
            readonly zones_mobilite: string[];
            readonly types_experience: string[];
            readonly prestations_acceptees: string[];
            readonly competences_conduite: string[];
            readonly permis: string[];
            readonly sports: components["schemas"]["ProfilSport"][];
            readonly competences_artistiques: components["schemas"]["ProfilCompetenceArtistique"][];
            readonly instruments: components["schemas"]["ProfilInstrument"][];
            readonly langues: components["schemas"]["ProfilLangue"][];
            readonly vehicules: components["schemas"]["ProfilVehicule"][];
            readonly photos: components["schemas"]["Photo"][];
            readonly mineur: components["schemas"]["Mineur"];
            reseaux_sociaux?: unknown;
            autres_caracteristiques?: unknown;
        };
        /**
         * @description Saisie d'un profil depuis le front (voir decisions/0001).
         *
         *     Les through models arrivent en listes imbriquées ; DRF ne sait pas les écrire
         *     seul, d'où le `create`/`update` explicite plus bas.
         */
        ProfilEcriture: {
            readonly id: number;
            sports?: components["schemas"]["SportEcriture"][];
            langues?: components["schemas"]["LangueEcriture"][];
            instruments?: components["schemas"]["InstrumentEcriture"][];
            competences_artistiques?: components["schemas"]["CompetenceArtistiqueEcriture"][];
            vehicules?: components["schemas"]["VehiculeEcriture"][];
            mineur?: components["schemas"]["MineurEcriture"] | null;
            reference?: string | null;
            nom: string;
            prenom: string;
            nom_artiste?: string;
            sexe?: components["schemas"]["SexeEnum"] | components["schemas"]["BlankEnum"];
            /** Format: date */
            date_naissance?: string | null;
            age_apparent_min?: number | null;
            age_apparent_max?: number | null;
            telephone?: string;
            email?: string;
            disponibilite?: components["schemas"]["DisponibiliteEnum"] | components["schemas"]["BlankEnum"];
            deja_figurant?: boolean;
            nombre_tournages?: number | null;
            taille_cm?: number | null;
            poids_kg?: number | null;
            pointure?: number | null;
            taille_vetement?: components["schemas"]["TailleVetementEnum"] | components["schemas"]["BlankEnum"];
            taille_pantalon?: number | null;
            tour_poitrine_cm?: number | null;
            tour_taille_cm?: number | null;
            tour_hanches_cm?: number | null;
            couleur_yeux?: components["schemas"]["CouleurYeuxEnum"] | components["schemas"]["BlankEnum"];
            couleur_cheveux?: components["schemas"]["CouleurCheveuxEnum"] | components["schemas"]["BlankEnum"];
            type_cheveux?: components["schemas"]["TypeCheveuxEnum"] | components["schemas"]["BlankEnum"];
            longueur_cheveux?: components["schemas"]["LongueurCheveuxEnum"] | components["schemas"]["BlankEnum"];
            cheveux_colores?: boolean;
            barbe?: boolean;
            moustache?: boolean;
            calvitie?: components["schemas"]["CalvitieEnum"] | components["schemas"]["BlankEnum"];
            tatouages_visibles?: boolean;
            piercings?: boolean;
            lunettes?: boolean;
            lentilles?: boolean;
            profil_multiculturel?: boolean;
            composition?: components["schemas"]["CompositionEnum"] | components["schemas"]["BlankEnum"];
            ville?: string;
            distance_max_km?: number | null;
            peut_dormir_sur_place?: boolean;
            vehicule_personnel_disponible?: boolean;
            besoin_transport?: boolean;
            /** Format: date */
            consentement_obtenu_le?: string | null;
            source_consentement?: string;
            actif?: boolean;
            reseaux_sociaux?: unknown;
            autres_caracteristiques?: unknown;
            notes?: unknown;
            departement?: number | null;
            registres?: number[];
            apparences?: number[];
            permis?: number[];
            competences_conduite?: number[];
            metiers?: number[];
            competences_particulieres?: number[];
            costumes?: number[];
            zones_mobilite?: number[];
            types_experience?: number[];
            prestations_acceptees?: number[];
        };
        ProfilInstrument: {
            readonly instrument: string;
            niveau: components["schemas"]["ProfilInstrumentNiveauEnum"];
            readonly niveau_libelle: string;
        };
        /**
         * @description * `1` - Débutant
         *     * `2` - Intermédiaire
         *     * `3` - Avancé
         *     * `4` - Professionnel
         * @enum {string}
         */
        ProfilInstrumentNiveauEnum: "1" | "2" | "3" | "4";
        ProfilLangue: {
            readonly langue: string;
            niveau: components["schemas"]["ProfilLangueNiveauEnum"];
            readonly niveau_libelle: string;
            readonly accent: string;
        };
        /**
         * @description * `A1` - A1 — Découverte
         *     * `A2` - A2 — Intermédiaire
         *     * `B1` - B1 — Seuil
         *     * `B2` - B2 — Avancé
         *     * `C1` - C1 — Autonome
         *     * `C2` - C2 — Maîtrise
         *     * `LM` - Langue maternelle
         * @enum {string}
         */
        ProfilLangueNiveauEnum: "A1" | "A2" | "B1" | "B2" | "C1" | "C2" | "LM";
        /**
         * @description Ce qu'affiche une comp card sur la planche : portrait, vitals, apparences.
         *
         *     Volontairement sans coordonnées ni date de naissance : la liste sert à
         *     repérer un profil, pas à le contacter. L'âge est dérivé, la date reste au détail.
         */
        ProfilListe: {
            readonly id: number;
            reference?: string | null;
            prenom: string;
            nom: string;
            nom_artiste?: string;
            sexe?: components["schemas"]["SexeEnum"] | components["schemas"]["BlankEnum"];
            readonly age: number;
            ville?: string;
            readonly departement: string;
            taille_cm?: number | null;
            couleur_yeux?: components["schemas"]["CouleurYeuxEnum"] | components["schemas"]["BlankEnum"];
            couleur_cheveux?: components["schemas"]["CouleurCheveuxEnum"] | components["schemas"]["BlankEnum"];
            readonly apparences: string[];
            readonly photos: components["schemas"]["Photo"][];
        };
        ProfilSport: {
            readonly sport: string;
            niveau: components["schemas"]["ProfilSportNiveauEnum"];
            readonly niveau_libelle: string;
        };
        /**
         * @description * `1` - Débutant
         *     * `2` - Amateur
         *     * `3` - Confirmé
         *     * `4` - Compétition
         *     * `5` - Professionnel
         * @enum {string}
         */
        ProfilSportNiveauEnum: "1" | "2" | "3" | "4" | "5";
        ProfilVehicule: {
            readonly type_vehicule: string;
            marque?: string;
            modele?: string;
            annee?: number | null;
        };
        /** @description Alimente les listes du rail de filtres. */
        Registre: {
            readonly id: number;
            nom: string;
        };
        /**
         * @description * `mere` - Mère
         *     * `pere` - Père
         *     * `tuteur` - Tuteur légal
         * @enum {string}
         */
        ResponsableLegalLienEnum: "mere" | "pere" | "tuteur";
        /**
         * @description Réponse de /api/session/ — déclarée pour que le contrat la documente.
         *
         *     `utilisateur` vaut null quand personne n'est connecté : l'endpoint reste
         *     accessible en anonyme, car c'est lui qui pose le cookie CSRF dont la page de
         *     connexion a besoin pour poster.
         */
        Session: {
            readonly utilisateur: string | null;
            readonly peut_saisir: boolean;
        };
        /**
         * @description * `H` - Homme
         *     * `F` - Femme
         *     * `A` - Autre
         * @enum {string}
         */
        SexeEnum: "H" | "F" | "A";
        Sport: {
            readonly id: number;
            nom: string;
            categorie?: components["schemas"]["CategorieEnum"] | components["schemas"]["BlankEnum"];
        };
        /** @description Une ligne de through model telle que la poste le formulaire. */
        SportEcriture: {
            niveau: string;
            sport: number;
        };
        /**
         * @description * `XS` - XS
         *     * `S` - S
         *     * `M` - M
         *     * `L` - L
         *     * `XL` - XL
         *     * `XXL` - XXL
         *     * `XXXL` - XXXL
         * @enum {string}
         */
        TailleVetementEnum: "XS" | "S" | "M" | "L" | "XL" | "XXL" | "XXXL";
        /**
         * @description * `raides` - Raides
         *     * `ondules` - Ondulés
         *     * `boucles` - Bouclés
         *     * `crepus` - Crépus
         * @enum {string}
         */
        TypeCheveuxEnum: "raides" | "ondules" | "boucles" | "crepus";
        /**
         * @description * `portrait` - Portrait
         *     * `pied` - En pied
         *     * `profil` - Profil
         *     * `recente` - Photo récente
         *     * `sans_lunettes` - Sans lunettes
         *     * `avec_lunettes` - Avec lunettes
         *     * `cheveux_actuels` - Cheveux actuels
         *     * `avec_barbe` - Avec barbe
         *     * `sans_barbe` - Sans barbe
         * @enum {string}
         */
        TypeEnum: "portrait" | "pied" | "profil" | "recente" | "sans_lunettes" | "avec_lunettes" | "cheveux_actuels" | "avec_barbe" | "sans_barbe";
        /** @description Alimente les listes du rail de filtres. */
        TypeExperience: {
            readonly id: number;
            nom: string;
        };
        /** @description Alimente les listes du rail de filtres. */
        TypePrestation: {
            readonly id: number;
            nom: string;
        };
        /** @description Alimente les listes du rail de filtres. */
        TypeVehicule: {
            readonly id: number;
            nom: string;
        };
        VehiculeEcriture: {
            type_vehicule: number;
            marque?: string;
            modele?: string;
            annee?: number | null;
        };
        /** @description Alimente les listes du rail de filtres. */
        ZoneMobilite: {
            readonly id: number;
            nom: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    accents_list: {
        parameters: {
            query?: {
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accent"][];
                };
            };
        };
    };
    accents_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) accent. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accent"];
                };
            };
        };
    };
    apparences_list: {
        parameters: {
            query?: {
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Apparence"][];
                };
            };
        };
    };
    apparences_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) apparence. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Apparence"];
                };
            };
        };
    };
    competences_artistiques_list: {
        parameters: {
            query?: {
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetenceArtistique"][];
                };
            };
        };
    };
    competences_artistiques_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) compétence artistique. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetenceArtistique"];
                };
            };
        };
    };
    competences_conduite_list: {
        parameters: {
            query?: {
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetenceConduite"][];
                };
            };
        };
    };
    competences_conduite_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) compétence de conduite. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetenceConduite"];
                };
            };
        };
    };
    competences_particulieres_list: {
        parameters: {
            query?: {
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetenceParticuliere"][];
                };
            };
        };
    };
    competences_particulieres_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) compétence particulière. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetenceParticuliere"];
                };
            };
        };
    };
    connexion_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Connexion"];
                "application/x-www-form-urlencoded": components["schemas"]["Connexion"];
                "multipart/form-data": components["schemas"]["Connexion"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    costumes_list: {
        parameters: {
            query?: {
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Costume"][];
                };
            };
        };
    };
    costumes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) costume. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Costume"];
                };
            };
        };
    };
    deconnexion_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    departements_list: {
        parameters: {
            query?: {
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Departement"][];
                };
            };
        };
    };
    departements_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) département. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Departement"];
                };
            };
        };
    };
    instruments_list: {
        parameters: {
            query?: {
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instrument"][];
                };
            };
        };
    };
    instruments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) instrument. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instrument"];
                };
            };
        };
    };
    langues_list: {
        parameters: {
            query?: {
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Langue"][];
                };
            };
        };
    };
    langues_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) langue. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Langue"];
                };
            };
        };
    };
    metiers_list: {
        parameters: {
            query?: {
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Metier"][];
                };
            };
        };
    };
    metiers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) métier. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Metier"];
                };
            };
        };
    };
    permis_list: {
        parameters: {
            query?: {
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Permis"][];
                };
            };
        };
    };
    permis_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) permis. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Permis"];
                };
            };
        };
    };
    photos_list: {
        parameters: {
            query?: {
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
                profil?: number;
                /**
                 * @description * `portrait` - Portrait
                 *     * `pied` - En pied
                 *     * `profil` - Profil
                 *     * `recente` - Photo récente
                 *     * `sans_lunettes` - Sans lunettes
                 *     * `avec_lunettes` - Avec lunettes
                 *     * `cheveux_actuels` - Cheveux actuels
                 *     * `avec_barbe` - Avec barbe
                 *     * `sans_barbe` - Sans barbe
                 */
                type?: "avec_barbe" | "avec_lunettes" | "cheveux_actuels" | "pied" | "portrait" | "profil" | "recente" | "sans_barbe" | "sans_lunettes";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoEcriture"][];
                };
            };
        };
    };
    photos_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhotoEcriture"];
                "application/x-www-form-urlencoded": components["schemas"]["PhotoEcriture"];
                "multipart/form-data": components["schemas"]["PhotoEcriture"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoEcriture"];
                };
            };
        };
    };
    photos_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) photo. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoEcriture"];
                };
            };
        };
    };
    photos_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) photo. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhotoEcriture"];
                "application/x-www-form-urlencoded": components["schemas"]["PhotoEcriture"];
                "multipart/form-data": components["schemas"]["PhotoEcriture"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoEcriture"];
                };
            };
        };
    };
    photos_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) photo. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    photos_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) photo. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPhotoEcriture"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPhotoEcriture"];
                "multipart/form-data": components["schemas"]["PatchedPhotoEcriture"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoEcriture"];
                };
            };
        };
    };
    prestations_list: {
        parameters: {
            query?: {
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypePrestation"][];
                };
            };
        };
    };
    prestations_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) type de prestation. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypePrestation"];
                };
            };
        };
    };
    profils_list: {
        parameters: {
            query?: {
                accent?: string;
                actif?: boolean;
                age_max?: number;
                age_min?: number;
                apparence?: string;
                avec_photo?: boolean;
                barbe?: boolean;
                besoin_transport?: boolean;
                /**
                 * @description * `non` - Non
                 *     * `degarni` - Dégarni
                 *     * `chauve` - Chauve
                 */
                calvitie?: "chauve" | "degarni" | "non";
                cheveux_colores?: boolean;
                /** @description Compétence artistique, éventuellement `Compétence:niveau_min` (1→4) */
                competence_artistique?: string;
                competence_conduite?: string;
                competence_particuliere?: string;
                /**
                 * @description * `seul` - Seul
                 *     * `couple` - Couple
                 *     * `fratrie` - Fratrie
                 *     * `famille` - Famille
                 *     * `amis` - Groupe d'amis
                 *     * `duo` - Duo
                 *     * `trio` - Trio
                 *     * `groupe_sportif` - Groupe sportif
                 *     * `groupe_pro` - Groupe professionnel
                 */
                composition?: "amis" | "couple" | "duo" | "famille" | "fratrie" | "groupe_pro" | "groupe_sportif" | "seul" | "trio";
                costume?: string;
                /**
                 * @description * `blond` - Blond
                 *     * `chatain` - Châtain
                 *     * `brun` - Brun
                 *     * `noir` - Noir
                 *     * `roux` - Roux
                 *     * `gris` - Gris
                 *     * `blanc` - Blanc
                 *     * `colore` - Coloré (fantaisie)
                 */
                couleur_cheveux?: "blanc" | "blond" | "brun" | "chatain" | "colore" | "gris" | "noir" | "roux";
                /**
                 * @description * `marron` - Marron
                 *     * `bleu` - Bleu
                 *     * `vert` - Vert
                 *     * `noisette` - Noisette
                 *     * `gris` - Gris
                 *     * `noir` - Noir
                 */
                couleur_yeux?: "bleu" | "gris" | "marron" | "noir" | "noisette" | "vert";
                deja_figurant?: boolean;
                departement?: string;
                /**
                 * @description * `immediate` - Immédiate
                 *     * `sous_48h` - Sous 48 h
                 *     * `week_ends` - Week-ends uniquement
                 *     * `vacances` - Vacances scolaires
                 *     * `sur_demande` - Sur demande
                 */
                disponibilite?: "immediate" | "sous_48h" | "sur_demande" | "vacances" | "week_ends";
                distance_max_km_min?: number;
                /** @description Instrument, éventuellement `Instrument:niveau_min` (1→4) */
                instrument?: string;
                /** @description Langue, éventuellement `Langue:niveau_min` (A1→C2, LM) */
                langue?: string;
                lentilles?: boolean;
                /**
                 * @description * `courts` - Courts
                 *     * `mi_longs` - Mi-longs
                 *     * `longs` - Longs
                 */
                longueur_cheveux?: "courts" | "longs" | "mi_longs";
                lunettes?: boolean;
                metier?: string;
                mineur?: boolean;
                moustache?: boolean;
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
                /** @description Un numéro de page de l'ensemble des résultats. */
                page?: number;
                /** @description Âge apparent contenant cette valeur */
                parait_age?: number;
                permis?: string;
                peut_dormir_sur_place?: boolean;
                piercings?: boolean;
                prestation?: string;
                profil_multiculturel?: boolean;
                /** @description Nom, prénom ou nom d'artiste */
                q?: string;
                region?: string;
                registre?: string;
                /**
                 * @description * `H` - Homme
                 *     * `F` - Femme
                 *     * `A` - Autre
                 */
                sexe?: "A" | "F" | "H";
                /** @description Sport, éventuellement `Sport:niveau_min` (1→5) */
                sport?: string;
                taille_max?: number;
                taille_min?: number;
                tatouages_visibles?: boolean;
                /**
                 * @description * `raides` - Raides
                 *     * `ondules` - Ondulés
                 *     * `boucles` - Bouclés
                 *     * `crepus` - Crépus
                 */
                type_cheveux?: "boucles" | "crepus" | "ondules" | "raides";
                type_experience?: string;
                vehicule_personnel_disponible?: boolean;
                ville?: string;
                zone_mobilite?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProfilListeList"];
                };
            };
        };
    };
    profils_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfilEcriture"];
                "application/x-www-form-urlencoded": components["schemas"]["ProfilEcriture"];
                "multipart/form-data": components["schemas"]["ProfilEcriture"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilEcriture"];
                };
            };
        };
    };
    profils_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) profil. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilDetail"];
                };
            };
        };
    };
    profils_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) profil. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfilEcriture"];
                "application/x-www-form-urlencoded": components["schemas"]["ProfilEcriture"];
                "multipart/form-data": components["schemas"]["ProfilEcriture"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilEcriture"];
                };
            };
        };
    };
    profils_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) profil. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    profils_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) profil. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProfilEcriture"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProfilEcriture"];
                "multipart/form-data": components["schemas"]["PatchedProfilEcriture"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilEcriture"];
                };
            };
        };
    };
    registres_list: {
        parameters: {
            query?: {
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Registre"][];
                };
            };
        };
    };
    registres_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) registre. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Registre"];
                };
            };
        };
    };
    session_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    sports_list: {
        parameters: {
            query?: {
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sport"][];
                };
            };
        };
    };
    sports_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) sport. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sport"];
                };
            };
        };
    };
    types_experience_list: {
        parameters: {
            query?: {
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeExperience"][];
                };
            };
        };
    };
    types_experience_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) type d'expérience. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeExperience"];
                };
            };
        };
    };
    types_vehicule_list: {
        parameters: {
            query?: {
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeVehicule"][];
                };
            };
        };
    };
    types_vehicule_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) type de véhicule. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeVehicule"];
                };
            };
        };
    };
    zones_mobilite_list: {
        parameters: {
            query?: {
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneMobilite"][];
                };
            };
        };
    };
    zones_mobilite_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un(une) valeur entière unique identifiant ce(cette) zone de mobilité. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneMobilite"];
                };
            };
        };
    };
}
