# Generated by Django 5.2.17 on 2026-08-13 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'accent',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Apparence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'apparence',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompetenceArtistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'compétence artistique',
                'verbose_name_plural': 'compétences artistiques',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompetenceConduite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'compétence de conduite',
                'verbose_name_plural': 'compétences de conduite',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompetenceParticuliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'compétence particulière',
                'verbose_name_plural': 'compétences particulières',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Costume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'costume',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'département',
                'verbose_name_plural': 'départements',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'instrument',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'langue',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Metier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'métier',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'permis',
                'verbose_name_plural': 'permis',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'région',
                'verbose_name_plural': 'régions',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Registre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'registre',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('categorie', models.CharField(blank=True, choices=[('collectif', 'Sport collectif'), ('individuel', 'Sport individuel')], max_length=12)),
            ],
            options={
                'verbose_name': 'sport',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': "type d'expérience",
                'verbose_name_plural': "types d'expérience",
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypePrestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'type de prestation',
                'verbose_name_plural': 'types de prestation',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'type de véhicule',
                'verbose_name_plural': 'types de véhicule',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZoneMobilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'zone de mobilité',
                'verbose_name_plural': 'zones de mobilité',
                'ordering': ['nom'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('nom_artiste', models.CharField(blank=True, max_length=150)),
                ('sexe', models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme'), ('A', 'Autre')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('age_apparent_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age_apparent_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('disponibilite', models.CharField(blank=True, choices=[('immediate', 'Immédiate'), ('sous_48h', 'Sous 48 h'), ('week_ends', 'Week-ends uniquement'), ('vacances', 'Vacances scolaires'), ('sur_demande', 'Sur demande')], max_length=15)),
                ('deja_figurant', models.BooleanField(default=False)),
                ('nombre_tournages', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('taille_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('poids_kg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pointure', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('taille_vetement', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=4)),
                ('taille_pantalon', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tour_poitrine_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tour_taille_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tour_hanches_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('couleur_yeux', models.CharField(blank=True, choices=[('marron', 'Marron'), ('bleu', 'Bleu'), ('vert', 'Vert'), ('noisette', 'Noisette'), ('gris', 'Gris'), ('noir', 'Noir')], max_length=20)),
                ('couleur_cheveux', models.CharField(blank=True, choices=[('blond', 'Blond'), ('chatain', 'Châtain'), ('brun', 'Brun'), ('noir', 'Noir'), ('roux', 'Roux'), ('gris', 'Gris'), ('blanc', 'Blanc'), ('colore', 'Coloré (fantaisie)')], max_length=20)),
                ('type_cheveux', models.CharField(blank=True, choices=[('raides', 'Raides'), ('ondules', 'Ondulés'), ('boucles', 'Bouclés'), ('crepus', 'Crépus')], max_length=20)),
                ('longueur_cheveux', models.CharField(blank=True, choices=[('courts', 'Courts'), ('mi_longs', 'Mi-longs'), ('longs', 'Longs')], max_length=20)),
                ('cheveux_colores', models.BooleanField(default=False)),
                ('barbe', models.BooleanField(default=False)),
                ('moustache', models.BooleanField(default=False)),
                ('calvitie', models.CharField(blank=True, choices=[('non', 'Non'), ('degarni', 'Dégarni'), ('chauve', 'Chauve')], max_length=10)),
                ('tatouages_visibles', models.BooleanField(default=False)),
                ('piercings', models.BooleanField(default=False)),
                ('lunettes', models.BooleanField(default=False)),
                ('lentilles', models.BooleanField(default=False)),
                ('profil_multiculturel', models.BooleanField(default=False)),
                ('composition', models.CharField(blank=True, choices=[('seul', 'Seul'), ('couple', 'Couple'), ('fratrie', 'Fratrie'), ('famille', 'Famille'), ('amis', "Groupe d'amis"), ('duo', 'Duo'), ('trio', 'Trio'), ('groupe_sportif', 'Groupe sportif'), ('groupe_pro', 'Groupe professionnel')], max_length=15)),
                ('ville', models.CharField(blank=True, max_length=120)),
                ('distance_max_km', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('peut_dormir_sur_place', models.BooleanField(default=False)),
                ('vehicule_personnel_disponible', models.BooleanField(default=False)),
                ('besoin_transport', models.BooleanField(default=False)),
                ('consentement_obtenu_le', models.DateField(blank=True, null=True)),
                ('source_consentement', models.CharField(blank=True, max_length=200)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_maj', models.DateTimeField(auto_now=True)),
                ('reseaux_sociaux', models.JSONField(blank=True, default=dict)),
                ('autres_caracteristiques', models.JSONField(blank=True, default=dict)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('apparences', models.ManyToManyField(blank=True, related_name='profils', to='casting.apparence')),
                ('competences_conduite', models.ManyToManyField(blank=True, related_name='profils', to='casting.competenceconduite')),
                ('competences_particulieres', models.ManyToManyField(blank=True, related_name='profils', to='casting.competenceparticuliere')),
                ('costumes', models.ManyToManyField(blank=True, related_name='profils', to='casting.costume')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profils', to='casting.departement')),
                ('metiers', models.ManyToManyField(blank=True, related_name='profils', to='casting.metier')),
                ('permis', models.ManyToManyField(blank=True, related_name='profils', to='casting.permis')),
            ],
            options={
                'verbose_name': 'profil',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('portrait', 'Portrait'), ('pied', 'En pied'), ('profil', 'Profil'), ('recente', 'Photo récente'), ('sans_lunettes', 'Sans lunettes'), ('avec_lunettes', 'Avec lunettes'), ('cheveux_actuels', 'Cheveux actuels'), ('avec_barbe', 'Avec barbe'), ('sans_barbe', 'Sans barbe')], max_length=20)),
                ('image', models.ImageField(upload_to='profils/%Y/%m/')),
                ('prise_le', models.DateField(blank=True, null=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='casting.profil')),
            ],
            options={
                'verbose_name': 'photo',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Mineur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable_legal_nom', models.CharField(max_length=150)),
                ('responsable_legal_prenom', models.CharField(max_length=150)),
                ('responsable_legal_lien', models.CharField(choices=[('mere', 'Mère'), ('pere', 'Père'), ('tuteur', 'Tuteur légal')], max_length=10)),
                ('responsable_legal_telephone', models.CharField(blank=True, max_length=30)),
                ('responsable_legal_email', models.EmailField(blank=True, max_length=254)),
                ('autorisation_parentale_signee', models.BooleanField(default=False)),
                ('autorisation_parentale_le', models.DateField(blank=True, null=True)),
                ('autorisation_travail_obtenue', models.BooleanField(default=False)),
                ('autorisation_travail_reference', models.CharField(blank=True, max_length=100)),
                ('autorisation_travail_expire_le', models.DateField(blank=True, null=True)),
                ('disponibilite_scolaire', models.CharField(blank=True, choices=[('vacances', 'Vacances scolaires uniquement'), ('mercredi', 'Mercredi et week-ends'), ('hors_scolaire', 'Hors temps scolaire'), ('sans_contrainte', 'Sans contrainte particulière')], max_length=20)),
                ('remarques', models.JSONField(blank=True, default=dict)),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mineur', to='casting.profil')),
            ],
            options={
                'verbose_name': 'mineur',
            },
        ),
        migrations.CreateModel(
            name='ProfilCompetenceArtistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('1', 'Débutant'), ('2', 'Amateur'), ('3', 'Confirmé'), ('4', 'Professionnel')], max_length=1)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casting.competenceartistique')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casting.profil')),
            ],
            options={
                'verbose_name': 'compétence artistique',
                'verbose_name_plural': 'compétences artistiques',
                'unique_together': {('profil', 'competence')},
            },
        ),
        migrations.AddField(
            model_name='profil',
            name='competences_artistiques',
            field=models.ManyToManyField(blank=True, related_name='profils', through='casting.ProfilCompetenceArtistique', to='casting.competenceartistique'),
        ),
        migrations.CreateModel(
            name='ProfilInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('1', 'Débutant'), ('2', 'Intermédiaire'), ('3', 'Avancé'), ('4', 'Professionnel')], max_length=1)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casting.instrument')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casting.profil')),
            ],
            options={
                'verbose_name': 'instrument pratiqué',
                'verbose_name_plural': 'instruments pratiqués',
                'unique_together': {('profil', 'instrument')},
            },
        ),
        migrations.AddField(
            model_name='profil',
            name='instruments',
            field=models.ManyToManyField(blank=True, related_name='profils', through='casting.ProfilInstrument', to='casting.instrument'),
        ),
        migrations.CreateModel(
            name='ProfilLangue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('A1', 'A1 — Découverte'), ('A2', 'A2 — Intermédiaire'), ('B1', 'B1 — Seuil'), ('B2', 'B2 — Avancé'), ('C1', 'C1 — Autonome'), ('C2', 'C2 — Maîtrise'), ('LM', 'Langue maternelle')], max_length=2)),
                ('accent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='casting.accent')),
                ('langue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casting.langue')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casting.profil')),
            ],
            options={
                'verbose_name': 'langue parlée',
                'verbose_name_plural': 'langues parlées',
                'unique_together': {('profil', 'langue')},
            },
        ),
        migrations.AddField(
            model_name='profil',
            name='langues',
            field=models.ManyToManyField(blank=True, related_name='profils', through='casting.ProfilLangue', to='casting.langue'),
        ),
        migrations.AddField(
            model_name='departement',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departements', to='casting.region'),
        ),
        migrations.AddField(
            model_name='profil',
            name='registres',
            field=models.ManyToManyField(blank=True, related_name='profils', to='casting.registre'),
        ),
        migrations.CreateModel(
            name='ProfilSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('1', 'Débutant'), ('2', 'Amateur'), ('3', 'Confirmé'), ('4', 'Compétition'), ('5', 'Professionnel')], max_length=1)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casting.profil')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casting.sport')),
            ],
            options={
                'verbose_name': 'sport pratiqué',
                'verbose_name_plural': 'sports pratiqués',
                'unique_together': {('profil', 'sport')},
            },
        ),
        migrations.AddField(
            model_name='profil',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='profils', through='casting.ProfilSport', to='casting.sport'),
        ),
        migrations.AddField(
            model_name='profil',
            name='types_experience',
            field=models.ManyToManyField(blank=True, related_name='profils', to='casting.typeexperience'),
        ),
        migrations.AddField(
            model_name='profil',
            name='prestations_acceptees',
            field=models.ManyToManyField(blank=True, related_name='profils', to='casting.typeprestation'),
        ),
        migrations.CreateModel(
            name='ProfilVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(blank=True, max_length=80)),
                ('modele', models.CharField(blank=True, max_length=80)),
                ('annee', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casting.profil')),
                ('type_vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casting.typevehicule')),
            ],
            options={
                'verbose_name': 'véhicule possédé',
                'verbose_name_plural': 'véhicules possédés',
                'unique_together': {('profil', 'type_vehicule', 'marque', 'modele')},
            },
        ),
        migrations.AddField(
            model_name='profil',
            name='vehicules',
            field=models.ManyToManyField(blank=True, related_name='profils', through='casting.ProfilVehicule', to='casting.typevehicule'),
        ),
        migrations.AddField(
            model_name='profil',
            name='zones_mobilite',
            field=models.ManyToManyField(blank=True, related_name='profils', to='casting.zonemobilite'),
        ),
    ]
